### ISSUE TITLE
Sugar for non-promises API

### ISSUE THREAD

**Issue by valeriangalliat** [themeleon/themeleon#13]
We should be able do this:

```js
this.push2(function (resolve, reject) {});
```

Which would be syntaxic sugar for:

```js
this.push(function () {
  return new Promise (function (resolve, reject) {});
});
```

Find a name other than `push2`, obviously.

**Comment by FWeinb** [comment]
How about overloading `this.push()` doing something like:
```js
var push = function(func){
 if (func.length === 2){
   // Special Promise behaviour (call with func(reject, resolve);) 
  } else {
   // Default 
  }
}
```

**Comment by valeriangalliat** [comment]
I like this!

**Comment by valeriangalliat** [comment]
In the end I'd rather recommend to completely drop Themeleon as a library and use 6to5 from today, like in [the default theme](https://github.com/SassDoc/sassdoc-theme-default/pull/58).
